### ISSUE TITLE
Failed installing package logisiticPCA

### ISSUE THREAD

**Issue by novitch** [andland/logisticPCA#19]
Hi,
I couldn't install your package. This get me an error:

** installing vignettes
** testing if installed package can be loaded
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'checkCompilerOptions' not found
Calls: ::: -> get
Execution halted
ERROR: loading failed
* removing ?/mnt/gpfs/pt2/lib/R_3.2.3/logisticPCA?
Installation failed: Command failed (1)

Do you have an idea to help me?

Thanks

**Comment by andland** [comment]
Sorry I didn't see this. logisticPCA is on CRAN, so you should be able to use `install.packages("logisticPCA")`
