### ISSUE TITLE
running logisticPCA on large matrix

### ISSUE THREAD

**Issue by ayanmandal120** [andland/logisticPCA#21]
Hi,

I'm trying to run logisticPCA on a 105x91802 binary matrix. I've been getting the following error:

Error: vector memory exhausted (limit reached?)

The line of code that's causing the issue is: qTq = crossprod(q), since this requires computing a 91802x91802 matrix which my laptop won't handle. 

Is there a workaround for this? Regular PCA still works for the matrix.

Thanks,
Ayan

**Comment by andland** [comment]
If it’s meaningful, you can try transposing the matrix before putting it into the function. Otherwise, I think not.

**Comment by ayanmandal120** [comment]
Transposing the matrix did work, but I'm not sure if I can interpret the resulting decomposition the same way. I think I'll just use logisticSVD, which seems to be able to handle this matrix.
